resolver: lts-21.25

packages:
  - .

extra-deps:
  - llvm-hs-9.0.1
  - llvm-hs-pure-9.0.0
  - llvm-hs-pretty-0.9.0.0

flags: {}

extra-include-dirs:
  - /usr/lib/llvm-14/include
  - /usr/lib/llvm-15/include
  - /usr/lib/llvm-16/include
  - /usr/local/opt/llvm@14/include
  - /usr/local/opt/llvm@15/include
  - /usr/include/llvm-14
  - /usr/include/llvm-15

extra-lib-dirs:
  - /usr/lib/llvm-14/lib
  - /usr/lib/llvm-15/lib
  - /usr/lib/llvm-16/lib
  - /usr/local/opt/llvm@14/lib
  - /usr/local/opt/llvm@15/lib
  - /usr/lib/x86_64-linux-gnu
  - /usr/lib/aarch64-linux-gnu
