# https://taskfile.dev

version: "3"

tasks:
  docker:build:
    desc: Build Docker image
    cmds:
      - docker-compose build

  docker:shell:
    desc: Open shell in Docker container
    cmds:
      - docker-compose run --rm karel-builder /bin/bash

  build:
    desc: Build Karel compiler in Docker
    cmds:
      - docker-compose run --rm karel-builder ./build.sh

  bnfc:
    desc: Generate parser with BNFC (in src/)
    cmds:
      - docker-compose run --rm karel-builder bnfc -m --haskell -o src/ karel.cf

  runtime:
    desc: Build runtime library
    cmds:
      - docker-compose run --rm karel-builder make -C runtime

  runtime:clean:
    desc: Clean runtime library
    cmds:
      - docker-compose run --rm karel-builder make -C runtime clean

  stack:build:
    desc: Build with Stack
    cmds:
      - docker-compose run --rm karel-builder stack build

  stack:clean:
    desc: Clean Stack build
    cmds:
      - docker-compose run --rm karel-builder stack clean

  test:
    desc: Run test compilation
    cmds:
      - docker-compose run --rm karel-builder ./karelc test/simple.kl

  clean:
    desc: Clean all build artifacts
    cmds:
      - rm -rf .stack-work/ karelc runtime/*.o runtime/*.a

  default:
    desc: Full build
    cmds:
      - task: build
    silent: true
