-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language karel.

module AbsKarel where

import Prelude (Char, Double, Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Karel
    = KarelGrammer Ident OptLineEnd [DirectiveBlock] [DeclBlock] [Stm] Ident [RoutineDefinitionBlock]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data DirectiveBlock
    = DirAlphabet
    | DirCMOS
    | DirCRT
    | DirNoBusy
    | DirNoLock
    | DirNoPauseS
    | DirRPMotion
    | DirComment Text
    | DirDefGroup Integer
    | DirDelay Integer
    | DirProp Integer
    | DirStackSiz Integer
    | DirTimeSliz Integer
    | DirEnv Ident
    | DirLock [ArrayIndexing]
    | DirNoAbort ErrorCommandBlock
    | DirNoPause ErrorCommandTPBlock
    | DirInclude Text
    | DirDefine Ident Expression
    | DirDefineConst Ident Integer
    | DirUndef Ident
    | DirIfdef Ident
    | DirIfndef Ident
    | DirIf Expression
    | DirElse
    | DirEndif
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ErrorCommandBlock = ECBCom | ECBError | ECBECom
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ErrorCommandTPBlock
    = ECTBECB ErrorCommandBlock | ECTBCom | ECTBErr | ECTBAnable
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data DeclBlock
    = DeclConst ConstDeclBlock
    | DeclType TypeDeclBlock
    | DeclVar VarDeclBlock
    | DeclRoutine RoutineDeclBlock
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ConstDeclBlock = CDB OptLineEnd [ConstDecl]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ConstDecl
    = CDIdent Ident Ident OptLineEnd
    | CDLiteral Ident Literal OptLineEnd
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TypeDeclBlock = TCB OptLineEnd [TypeDecl]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TypeDecl
    = TDeclU Ident Ident UserType OptLineEnd
    | TUser Ident UserType OptLineEnd
    | TUserD UserType OptLineEnd
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data VarDeclBlock = VDB OptLineEnd [VarDecl]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data VarDecl
    = VarDIden Ident OptLineEnd VarDecl
    | VarDDtype Ident MemTypes FromBlock DataTypes
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RoutineDeclBlock
    = RoutineDeclarationBlock Ident RoutineParameter FromBlock
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RoutineParameter
    = RoutineParamBrack [ParameterField]
    | RoutineReturn [ParameterField] ReturnDataTypes
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ParameterField
    = ParamFieldIdent ParamIdent ParameterDataTypes
    | ParamFieldDecl ParamIdent [ParamIdent] ParameterDataTypes
    | ParamDefaultDecl ParamIdent [ParamIdent] ParameterDataTypes Expression
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ParamIdent = ParamType Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RoutineDefinitionBlock
    = RoutineDefineBlock Ident OptLineEnd [DeclBlock] [Stm] Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FromBlock = FromBIdent Ident | FromBEmpty Empty
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data GlobalCondition
    = GCBase GlobalCondition
    | GCError [ArrayIndexing]
    | GCEvent [ArrayIndexing]
    | GCSemaphore [ArrayIndexing]
    | GCPowerUp
    | GCAbort GlobalConditionSelect
    | GCPause GlobalConditionSelect
    | GCCONTINUE GlobalConditionSelect
    | GCVarAccess GlobalConditionBool
    | GCPortCond Ident Expression Sign
    | GCNotPortCond Ident Expression Sign
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data GlobalConditionSelect = GCSProg Expression | GCSEmpty Empty
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data GlobalConditionBool
    = GCBEqual Ident GlobalConditionVarSelect
    | GCBNEqual Ident GlobalConditionVarSelect
    | GCBLess Ident GlobalConditionVarSelect
    | GCBLessEQ Ident GlobalConditionVarSelect
    | GCBGread Ident GlobalConditionVarSelect
    | GCBGEQ Ident GlobalConditionVarSelect
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data GlobalConditionVarSelect
    = GCVSBase Constant | GCVSEval Expression
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ConditionHandlerAction
    = CHAEmpty Empty
    | CHANoAbort
    | CHANoPause
    | CHAUnPause
    | CHANoMessage
    | CHARestore
    | CHAHold Groups
    | CHAUnHold Groups
    | CHAResum Groups
    | CHAStop Groups
    | CHACancel Groups
    | CHAEnable Expression
    | CHADisable Expression
    | CHASignalEvent Expression
    | CHASignalSema Expression
    | CHAIdent Ident
    | CHAPulse PulseOut Expression Integer
    | CHAAbort
    | CHAAbortProg Expression
    | CHAContinue
    | CHAContProg Expression
    | CHAPause
    | CHAPauseProg Expression
    | CHAVarAccess VarAccess Ident Expression
    | CHAVarAccEval VarAccess Expression
    | CHAVarAccConst VarAccess Constant
    | CHAPortVA Integer Expression VarAccess
    | CHAPortEval Integer Expression Expression
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Stm
    = SAttach
    | SRelease
    | SAbort
    | SAbortP [ArrayIndexing]
    | SAssign Ident Expression
    | SCloseFile Ident
    | SCloseHand Integer
    | SDelay Integer
    | SConnect Integer
    | SDisable [ArrayIndexing]
    | SDisconectT Integer
    | SEnable [ArrayIndexing]
    | SOpenHand Integer
    | SPurge [ArrayIndexing]
    | SRelax Integer
    | SSignal [ArrayIndexing]
    | SCancel
    | SCancelFile Ident
    | SCancelGroup Groups
    | SCallparamExp Ident [Expression]
    | SForTo Ident Integer Integer [Stm]
    | SForDownTo Ident Integer Integer [Stm]
    | SGoTo Ident
    | SGo_To Ident
    | SHold
    | SHoleGroup Groups
    | SIfThen Expression [Stm]
    | SIfThenElse Expression [Stm] [Stm]
    | SPause
    | SPauseProgram [ArrayIndexing]
    | SPulse PulseOut [ArrayIndexing] Expression Nwait
    | SOpenFile Ident Expression Expression
    | SReadIdent Ident [ReadItem]
    | SRead [ReadItem]
    | SReturn
    | SReturnExp Expression
    | SUsing [VarAccess] [Stm]
    | SUnHold
    | SUnHoldExt Groups
    | SStop
    | SStopExt Groups
    | SSelect Expression [CaseStm]
    | SSelectElse Expression [CaseStm] [Stm]
    | SRepeat [Stm] Expression
    | SResum
    | SResumGroup Groups
    | SWait WaitSelect
    | SWhile Expression [Stm]
    | SWrite Ident [WriteItem]
    | SCondition [ArrayIndexing] ConditionWhenStm
    | SConditionWith [ArrayIndexing] [ConditionWithStm] ConditionWhenStm
    | SMove Expression
    | SMoveLinear Expression
    | SMoveJoint Expression
    | SMoveCircular Expression Expression
    | SGetVar Expression Ident Expression Ident
    | SSetVar Expression Ident Expression Expression Ident
    | SGetPort Expression Ident
    | SSetPort Expression Expression Ident
    | SGetReg Expression Ident Ident
    | SSetReg Expression Expression Ident
    | SGetTPE Ident Ident Ident
    | SSetTPE Ident Ident Ident
    | SClearTPE
    | SGetJPos Expression Ident Ident
    | SSetJPos Expression Ident Ident
    | SGetPosReg Expression Ident Ident
    | SSetPosReg Expression Ident Ident
    | SGetPosTPE Ident Ident Ident
    | SSetPosTPE Ident Ident Ident
    | SMsg Expression Ident
    | SActScreen Ident
    | SDeactScreen Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ConditionWhenStm
    = CWSTMWhen GlobalConditionList [ConditionHandlerAction]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ConditionWithStm
    = CWSTMWith Ident [ArrayIndexing] Ident Expression
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data GlobalConditionList
    = GCLAnd GlobalCondition GlobalCondition
    | GCLOr GlobalCondition GlobalCondition
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Groups = GroupBase [ArrayIndexing]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data WaitSelect
    = WaitSelectGC GlobalCondition
    | WaitSelectAND GlobalCondition GlobalCondition
    | WaitSelectOR GlobalCondition GlobalCondition
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data CaseStm = SCase [ArrayIndexing] [Stm]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data VarAccess
    = SVarAccess Ident
    | SVarAccessIdent VarAccess Ident
    | SVarAccessArray VarAccess [ArrayIndexing]
    | SVarAccessPath VarAccess Expression Expression
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ReadItem = SReadItem CR FormatSpec
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data WriteItem
    = SWriteItem CR FormatSpec | SWriteItemExp Expression FormatSpec
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FormatSpec
    = FormatSpec1 Expression
    | FormatSpec2 Expression Expression
    | FormatSpecEmpty Empty
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data CR = RIDefault | RICar Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data PulseOut = SSPulseOut | SSPulseRDO
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Nwait = SSWait | SSWaitEmapty Empty
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Expression
    = EBrack Expression
    | EEqual Expression Expression
    | ENEqual Expression Expression
    | ELess Expression Expression
    | ELeq Expression Expression
    | Egret Expression Expression
    | Egeq Expression Expression
    | Esp Expression Expression
    | EAdd Expression Expression
    | ESub Expression Expression
    | EOR Expression Expression
    | EPlus Expression
    | EMinus Expression
    | EMul Expression Expression
    | EAdiv Expression Expression
    | EAnd Expression Expression
    | EMOD Expression Expression
    | EDiv Expression Expression
    | ENot Expression Expression
    | EDot Expression Expression
    | EAt Expression Expression
    | EHash Expression Expression
    | EIdent Ident
    | EQString Text
    | EDouble Double
    | EInt Integer
    | EABS Expression
    | EACOS Expression
    | EASIN Expression
    | EATAN2 Expression Expression
    | ECOS Expression
    | ESin Expression
    | ETan Expression
    | ESqrt Expression
    | ELn Expression
    | EExp Expression
    | ETrunc Expression
    | ERound Expression
    | EStrlen Expression
    | ESubstr Expression Expression Expression
    | EChr Expression
    | EOrd Expression
    | EUninitd Expression
    | ECurPos Expression Expression
    | ECurJPos Expression Expression
    | EPosToJ Expression Expression
    | EJToPos Expression Expression
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data UserType
    = UserTypeDT Ident DataTypes
    | UserTypeStruct Ident OptLineEnd [VarDecl]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Empty = EmpyType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data MemTypes = MemTypeDMOS | MemTypeDRAM | MemTypeEmpty Empty
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ReturnDataTypes
    = RDTIdent Ident
    | RDTChar Char
    | RDTInt
    | RDTReal
    | RDTBool
    | RDTVector
    | RDTConfig
    | RDTCommon
    | RDTPos PositionDataTypes Integer
    | RDTString
    | RDTArray [ReturnArrayIndex] StructuredArrayType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ParameterDataTypes
    = PDTIdent Ident
    | PDTChar Char
    | PDTInt
    | PDTReal
    | PDTBool
    | PDTVector
    | PDTVis
    | PDTModel
    | PDTCam
    | PDTFile
    | PDTConf
    | PDTPath PathDataType
    | PDTCommon
    | PDTPos PositionDataTypes Integer
    | PDTString
    | PDTArray DataTypes StructuredArrayType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data DataTypes
    = DTString Integer
    | DTArray [ArrayIndexing] StructuredArrayType
    | DTStruct StructuredArrayType
    | DTParam ParameterDataTypes
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data StructuredArrayType = SATShort | SATByte
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data PathDataType
    = PathDTHeader Ident
    | PathDTNode Ident
    | PathDtEmpty Empty
    | PathDtHeaderExt Ident Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data PositionDataTypes
    = PDTyPos
    | PDTyXYZ
    | PDTyJPos
    | PDTyJPos1
    | PDTyJPos2
    | PDTyJPos3
    | PDTyJPos4
    | PDTyJPos5
    | PDTyJPos6
    | PDTyJPos7
    | PDTyJPos8
    | PDTyJPos9
    | PDTyXYZEXT
    | PDTyGAssoc
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data BoolDataTypes = BDTTrue | BDTFalse
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ArrayIndexing = IntArrayIndex Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ReturnArrayIndex
    = ReturnArrayInteger Integer | ReturnArrayAster
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Sign = SignPlus | SignMinus | SignEmpty Empty
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Literal
    = LiteralInteger Integer
    | LiteralDouble Double
    | LiteralQuoted Text
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Text = TextString String | TextQuotedString QuotedString
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Constant = ConstLiteral Literal | ConstIdent Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data OptLineEnd = OptLineEndLineEnd LineEnd | OptLineEndEmpty Empty
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype QuotedString = QuotedString String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype LineEnd = LineEnd String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

