-- File generated by the BNF Converter (bnfc 2.9.6.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module SkelKarel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsKarel

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsKarel.Ident -> Result
transIdent x = case x of
  AbsKarel.Ident string -> failure x

transQuotedString :: AbsKarel.QuotedString -> Result
transQuotedString x = case x of
  AbsKarel.QuotedString string -> failure x

transLineEnd :: AbsKarel.LineEnd -> Result
transLineEnd x = case x of
  AbsKarel.LineEnd string -> failure x

transKarel :: AbsKarel.Karel -> Result
transKarel x = case x of
  AbsKarel.KarelGrammer ident1 optlineend directiveblocks declblocks stms ident2 routinedefinitionblocks -> failure x

transDirectiveBlock :: AbsKarel.DirectiveBlock -> Result
transDirectiveBlock x = case x of
  AbsKarel.DirAlphabet -> failure x
  AbsKarel.DirCMOS -> failure x
  AbsKarel.DirCRT -> failure x
  AbsKarel.DirNoBusy -> failure x
  AbsKarel.DirNoLock -> failure x
  AbsKarel.DirNoPauseS -> failure x
  AbsKarel.DirRPMotion -> failure x
  AbsKarel.DirComment text -> failure x
  AbsKarel.DirDefGroup integer -> failure x
  AbsKarel.DirDelay integer -> failure x
  AbsKarel.DirProp integer -> failure x
  AbsKarel.DirStackSiz integer -> failure x
  AbsKarel.DirTimeSliz integer -> failure x
  AbsKarel.DirEnv ident -> failure x
  AbsKarel.DirLock arrayindexings -> failure x
  AbsKarel.DirNoAbort errorcommandblock -> failure x
  AbsKarel.DirNoPause errorcommandtpblock -> failure x
  AbsKarel.DirInclude text -> failure x
  AbsKarel.DirDefine ident expression -> failure x
  AbsKarel.DirDefineConst ident integer -> failure x
  AbsKarel.DirUndef ident -> failure x
  AbsKarel.DirIfdef ident -> failure x
  AbsKarel.DirIfndef ident -> failure x
  AbsKarel.DirIf expression -> failure x
  AbsKarel.DirElse -> failure x
  AbsKarel.DirEndif -> failure x

transErrorCommandBlock :: AbsKarel.ErrorCommandBlock -> Result
transErrorCommandBlock x = case x of
  AbsKarel.ECBCom -> failure x
  AbsKarel.ECBError -> failure x
  AbsKarel.ECBECom -> failure x

transErrorCommandTPBlock :: AbsKarel.ErrorCommandTPBlock -> Result
transErrorCommandTPBlock x = case x of
  AbsKarel.ECTBECB errorcommandblock -> failure x
  AbsKarel.ECTBCom -> failure x
  AbsKarel.ECTBErr -> failure x
  AbsKarel.ECTBAnable -> failure x

transDeclBlock :: AbsKarel.DeclBlock -> Result
transDeclBlock x = case x of
  AbsKarel.DeclConst constdeclblock -> failure x
  AbsKarel.DeclType typedeclblock -> failure x
  AbsKarel.DeclVar vardeclblock -> failure x
  AbsKarel.DeclRoutine routinedeclblock -> failure x

transConstDeclBlock :: AbsKarel.ConstDeclBlock -> Result
transConstDeclBlock x = case x of
  AbsKarel.CDB optlineend constdecls -> failure x

transConstDecl :: AbsKarel.ConstDecl -> Result
transConstDecl x = case x of
  AbsKarel.CDIdent ident1 ident2 optlineend -> failure x
  AbsKarel.CDLiteral ident literal optlineend -> failure x

transTypeDeclBlock :: AbsKarel.TypeDeclBlock -> Result
transTypeDeclBlock x = case x of
  AbsKarel.TCB optlineend typedecls -> failure x

transTypeDecl :: AbsKarel.TypeDecl -> Result
transTypeDecl x = case x of
  AbsKarel.TDeclU ident1 ident2 usertype optlineend -> failure x
  AbsKarel.TUser ident usertype optlineend -> failure x
  AbsKarel.TUserD usertype optlineend -> failure x

transVarDeclBlock :: AbsKarel.VarDeclBlock -> Result
transVarDeclBlock x = case x of
  AbsKarel.VDB optlineend vardecls -> failure x

transVarDecl :: AbsKarel.VarDecl -> Result
transVarDecl x = case x of
  AbsKarel.VarDIden ident optlineend vardecl -> failure x
  AbsKarel.VarDDtype ident memtypes fromblock datatypes -> failure x

transRoutineDeclBlock :: AbsKarel.RoutineDeclBlock -> Result
transRoutineDeclBlock x = case x of
  AbsKarel.RoutineDeclarationBlock ident routineparameter fromblock -> failure x

transRoutineParameter :: AbsKarel.RoutineParameter -> Result
transRoutineParameter x = case x of
  AbsKarel.RoutineParamBrack parameterfields -> failure x
  AbsKarel.RoutineReturn parameterfields returndatatypes -> failure x

transParameterField :: AbsKarel.ParameterField -> Result
transParameterField x = case x of
  AbsKarel.ParamFieldIdent paramident parameterdatatypes -> failure x
  AbsKarel.ParamFieldDecl paramident paramidents parameterdatatypes -> failure x
  AbsKarel.ParamDefaultDecl paramident paramidents parameterdatatypes expression -> failure x

transParamIdent :: AbsKarel.ParamIdent -> Result
transParamIdent x = case x of
  AbsKarel.ParamType ident -> failure x

transRoutineDefinitionBlock :: AbsKarel.RoutineDefinitionBlock -> Result
transRoutineDefinitionBlock x = case x of
  AbsKarel.RoutineDefineBlock ident1 optlineend declblocks stms ident2 -> failure x

transFromBlock :: AbsKarel.FromBlock -> Result
transFromBlock x = case x of
  AbsKarel.FromBIdent ident -> failure x
  AbsKarel.FromBEmpty empty -> failure x

transGlobalCondition :: AbsKarel.GlobalCondition -> Result
transGlobalCondition x = case x of
  AbsKarel.GCBase globalcondition -> failure x
  AbsKarel.GCError arrayindexings -> failure x
  AbsKarel.GCEvent arrayindexings -> failure x
  AbsKarel.GCSemaphore arrayindexings -> failure x
  AbsKarel.GCPowerUp -> failure x
  AbsKarel.GCAbort globalconditionselect -> failure x
  AbsKarel.GCPause globalconditionselect -> failure x
  AbsKarel.GCCONTINUE globalconditionselect -> failure x
  AbsKarel.GCVarAccess globalconditionbool -> failure x
  AbsKarel.GCPortCond ident expression sign -> failure x
  AbsKarel.GCNotPortCond ident expression sign -> failure x

transGlobalConditionSelect :: AbsKarel.GlobalConditionSelect -> Result
transGlobalConditionSelect x = case x of
  AbsKarel.GCSProg expression -> failure x
  AbsKarel.GCSEmpty empty -> failure x

transGlobalConditionBool :: AbsKarel.GlobalConditionBool -> Result
transGlobalConditionBool x = case x of
  AbsKarel.GCBEqual ident globalconditionvarselect -> failure x
  AbsKarel.GCBNEqual ident globalconditionvarselect -> failure x
  AbsKarel.GCBLess ident globalconditionvarselect -> failure x
  AbsKarel.GCBLessEQ ident globalconditionvarselect -> failure x
  AbsKarel.GCBGread ident globalconditionvarselect -> failure x
  AbsKarel.GCBGEQ ident globalconditionvarselect -> failure x

transGlobalConditionVarSelect :: AbsKarel.GlobalConditionVarSelect -> Result
transGlobalConditionVarSelect x = case x of
  AbsKarel.GCVSBase constant -> failure x
  AbsKarel.GCVSEval expression -> failure x

transConditionHandlerAction :: AbsKarel.ConditionHandlerAction -> Result
transConditionHandlerAction x = case x of
  AbsKarel.CHAEmpty empty -> failure x
  AbsKarel.CHANoAbort -> failure x
  AbsKarel.CHANoPause -> failure x
  AbsKarel.CHAUnPause -> failure x
  AbsKarel.CHANoMessage -> failure x
  AbsKarel.CHARestore -> failure x
  AbsKarel.CHAHold groups -> failure x
  AbsKarel.CHAUnHold groups -> failure x
  AbsKarel.CHAResum groups -> failure x
  AbsKarel.CHAStop groups -> failure x
  AbsKarel.CHACancel groups -> failure x
  AbsKarel.CHAEnable expression -> failure x
  AbsKarel.CHADisable expression -> failure x
  AbsKarel.CHASignalEvent expression -> failure x
  AbsKarel.CHASignalSema expression -> failure x
  AbsKarel.CHAIdent ident -> failure x
  AbsKarel.CHAPulse pulseout expression integer -> failure x
  AbsKarel.CHAAbort -> failure x
  AbsKarel.CHAAbortProg expression -> failure x
  AbsKarel.CHAContinue -> failure x
  AbsKarel.CHAContProg expression -> failure x
  AbsKarel.CHAPause -> failure x
  AbsKarel.CHAPauseProg expression -> failure x
  AbsKarel.CHAVarAccess varaccess ident expression -> failure x
  AbsKarel.CHAVarAccEval varaccess expression -> failure x
  AbsKarel.CHAVarAccConst varaccess constant -> failure x
  AbsKarel.CHAPortVA integer expression varaccess -> failure x
  AbsKarel.CHAPortEval integer expression1 expression2 -> failure x

transStm :: AbsKarel.Stm -> Result
transStm x = case x of
  AbsKarel.SAttach -> failure x
  AbsKarel.SRelease -> failure x
  AbsKarel.SAbort -> failure x
  AbsKarel.SAbortP arrayindexings -> failure x
  AbsKarel.SAssign ident expression -> failure x
  AbsKarel.SCloseFile ident -> failure x
  AbsKarel.SCloseHand integer -> failure x
  AbsKarel.SDelay integer -> failure x
  AbsKarel.SConnect integer -> failure x
  AbsKarel.SDisable arrayindexings -> failure x
  AbsKarel.SDisconectT integer -> failure x
  AbsKarel.SEnable arrayindexings -> failure x
  AbsKarel.SOpenHand integer -> failure x
  AbsKarel.SPurge arrayindexings -> failure x
  AbsKarel.SRelax integer -> failure x
  AbsKarel.SSignal arrayindexings -> failure x
  AbsKarel.SCancel -> failure x
  AbsKarel.SCancelFile ident -> failure x
  AbsKarel.SCancelGroup groups -> failure x
  AbsKarel.SCallparamExp ident expressions -> failure x
  AbsKarel.SForTo ident integer1 integer2 stms -> failure x
  AbsKarel.SForDownTo ident integer1 integer2 stms -> failure x
  AbsKarel.SGoTo ident -> failure x
  AbsKarel.SGo_To ident -> failure x
  AbsKarel.SHold -> failure x
  AbsKarel.SHoleGroup groups -> failure x
  AbsKarel.SIfThen expression stms -> failure x
  AbsKarel.SIfThenElse expression stms1 stms2 -> failure x
  AbsKarel.SPause -> failure x
  AbsKarel.SPauseProgram arrayindexings -> failure x
  AbsKarel.SPulse pulseout arrayindexings expression nwait -> failure x
  AbsKarel.SOpenFile ident expression1 expression2 -> failure x
  AbsKarel.SReadIdent ident readitems -> failure x
  AbsKarel.SRead readitems -> failure x
  AbsKarel.SReturn -> failure x
  AbsKarel.SReturnExp expression -> failure x
  AbsKarel.SUsing varaccesss stms -> failure x
  AbsKarel.SUnHold -> failure x
  AbsKarel.SUnHoldExt groups -> failure x
  AbsKarel.SStop -> failure x
  AbsKarel.SStopExt groups -> failure x
  AbsKarel.SSelect expression casestms -> failure x
  AbsKarel.SSelectElse expression casestms stms -> failure x
  AbsKarel.SRepeat stms expression -> failure x
  AbsKarel.SResum -> failure x
  AbsKarel.SResumGroup groups -> failure x
  AbsKarel.SWait waitselect -> failure x
  AbsKarel.SWhile expression stms -> failure x
  AbsKarel.SWrite ident writeitems -> failure x
  AbsKarel.SCondition arrayindexings conditionwhenstm -> failure x
  AbsKarel.SConditionWith arrayindexings conditionwithstms conditionwhenstm -> failure x
  AbsKarel.SMove expression -> failure x
  AbsKarel.SMoveLinear expression -> failure x
  AbsKarel.SMoveJoint expression -> failure x
  AbsKarel.SMoveCircular expression1 expression2 -> failure x
  AbsKarel.SGetVar expression1 ident1 expression2 ident2 -> failure x
  AbsKarel.SSetVar expression1 ident1 expression2 expression3 ident2 -> failure x
  AbsKarel.SGetPort expression ident -> failure x
  AbsKarel.SSetPort expression1 expression2 ident -> failure x
  AbsKarel.SGetReg expression ident1 ident2 -> failure x
  AbsKarel.SSetReg expression1 expression2 ident -> failure x
  AbsKarel.SGetTPE ident1 ident2 ident3 -> failure x
  AbsKarel.SSetTPE ident1 ident2 ident3 -> failure x
  AbsKarel.SClearTPE -> failure x
  AbsKarel.SGetJPos expression ident1 ident2 -> failure x
  AbsKarel.SSetJPos expression ident1 ident2 -> failure x
  AbsKarel.SGetPosReg expression ident1 ident2 -> failure x
  AbsKarel.SSetPosReg expression ident1 ident2 -> failure x
  AbsKarel.SGetPosTPE ident1 ident2 ident3 -> failure x
  AbsKarel.SSetPosTPE ident1 ident2 ident3 -> failure x
  AbsKarel.SMsg expression ident -> failure x
  AbsKarel.SActScreen ident -> failure x
  AbsKarel.SDeactScreen ident -> failure x

transConditionWhenStm :: AbsKarel.ConditionWhenStm -> Result
transConditionWhenStm x = case x of
  AbsKarel.CWSTMWhen globalconditionlist conditionhandleractions -> failure x

transConditionWithStm :: AbsKarel.ConditionWithStm -> Result
transConditionWithStm x = case x of
  AbsKarel.CWSTMWith ident1 arrayindexings ident2 expression -> failure x

transGlobalConditionList :: AbsKarel.GlobalConditionList -> Result
transGlobalConditionList x = case x of
  AbsKarel.GCLAnd globalcondition1 globalcondition2 -> failure x
  AbsKarel.GCLOr globalcondition1 globalcondition2 -> failure x

transGroups :: AbsKarel.Groups -> Result
transGroups x = case x of
  AbsKarel.GroupBase arrayindexings -> failure x

transWaitSelect :: AbsKarel.WaitSelect -> Result
transWaitSelect x = case x of
  AbsKarel.WaitSelectGC globalcondition -> failure x
  AbsKarel.WaitSelectAND globalcondition1 globalcondition2 -> failure x
  AbsKarel.WaitSelectOR globalcondition1 globalcondition2 -> failure x

transCaseStm :: AbsKarel.CaseStm -> Result
transCaseStm x = case x of
  AbsKarel.SCase arrayindexings stms -> failure x

transVarAccess :: AbsKarel.VarAccess -> Result
transVarAccess x = case x of
  AbsKarel.SVarAccess ident -> failure x
  AbsKarel.SVarAccessIdent varaccess ident -> failure x
  AbsKarel.SVarAccessArray varaccess arrayindexings -> failure x
  AbsKarel.SVarAccessPath varaccess expression1 expression2 -> failure x

transReadItem :: AbsKarel.ReadItem -> Result
transReadItem x = case x of
  AbsKarel.SReadItem cr formatspec -> failure x

transWriteItem :: AbsKarel.WriteItem -> Result
transWriteItem x = case x of
  AbsKarel.SWriteItem cr formatspec -> failure x
  AbsKarel.SWriteItemExp expression formatspec -> failure x

transFormatSpec :: AbsKarel.FormatSpec -> Result
transFormatSpec x = case x of
  AbsKarel.FormatSpec1 expression -> failure x
  AbsKarel.FormatSpec2 expression1 expression2 -> failure x
  AbsKarel.FormatSpecEmpty empty -> failure x

transCR :: AbsKarel.CR -> Result
transCR x = case x of
  AbsKarel.RIDefault -> failure x
  AbsKarel.RICar ident -> failure x

transPulseOut :: AbsKarel.PulseOut -> Result
transPulseOut x = case x of
  AbsKarel.SSPulseOut -> failure x
  AbsKarel.SSPulseRDO -> failure x

transNwait :: AbsKarel.Nwait -> Result
transNwait x = case x of
  AbsKarel.SSWait -> failure x
  AbsKarel.SSWaitEmapty empty -> failure x

transExpression :: AbsKarel.Expression -> Result
transExpression x = case x of
  AbsKarel.EBrack expression -> failure x
  AbsKarel.EEqual expression1 expression2 -> failure x
  AbsKarel.ENEqual expression1 expression2 -> failure x
  AbsKarel.ELess expression1 expression2 -> failure x
  AbsKarel.ELeq expression1 expression2 -> failure x
  AbsKarel.Egret expression1 expression2 -> failure x
  AbsKarel.Egeq expression1 expression2 -> failure x
  AbsKarel.Esp expression1 expression2 -> failure x
  AbsKarel.EAdd expression1 expression2 -> failure x
  AbsKarel.ESub expression1 expression2 -> failure x
  AbsKarel.EOR expression1 expression2 -> failure x
  AbsKarel.EPlus expression -> failure x
  AbsKarel.EMinus expression -> failure x
  AbsKarel.EMul expression1 expression2 -> failure x
  AbsKarel.EAdiv expression1 expression2 -> failure x
  AbsKarel.EAnd expression1 expression2 -> failure x
  AbsKarel.EMOD expression1 expression2 -> failure x
  AbsKarel.EDiv expression1 expression2 -> failure x
  AbsKarel.ENot expression1 expression2 -> failure x
  AbsKarel.EDot expression1 expression2 -> failure x
  AbsKarel.EAt expression1 expression2 -> failure x
  AbsKarel.EHash expression1 expression2 -> failure x
  AbsKarel.EIdent ident -> failure x
  AbsKarel.EQString text -> failure x
  AbsKarel.EDouble double -> failure x
  AbsKarel.EInt integer -> failure x
  AbsKarel.EABS expression -> failure x
  AbsKarel.EACOS expression -> failure x
  AbsKarel.EASIN expression -> failure x
  AbsKarel.EATAN2 expression1 expression2 -> failure x
  AbsKarel.ECOS expression -> failure x
  AbsKarel.ESin expression -> failure x
  AbsKarel.ETan expression -> failure x
  AbsKarel.ESqrt expression -> failure x
  AbsKarel.ELn expression -> failure x
  AbsKarel.EExp expression -> failure x
  AbsKarel.ETrunc expression -> failure x
  AbsKarel.ERound expression -> failure x
  AbsKarel.EStrlen expression -> failure x
  AbsKarel.ESubstr expression1 expression2 expression3 -> failure x
  AbsKarel.EChr expression -> failure x
  AbsKarel.EOrd expression -> failure x
  AbsKarel.EUninitd expression -> failure x
  AbsKarel.ECurPos expression1 expression2 -> failure x
  AbsKarel.ECurJPos expression1 expression2 -> failure x
  AbsKarel.EPosToJ expression1 expression2 -> failure x
  AbsKarel.EJToPos expression1 expression2 -> failure x

transUserType :: AbsKarel.UserType -> Result
transUserType x = case x of
  AbsKarel.UserTypeDT ident datatypes -> failure x
  AbsKarel.UserTypeStruct ident optlineend vardecls -> failure x

transEmpty :: AbsKarel.Empty -> Result
transEmpty x = case x of
  AbsKarel.EmpyType -> failure x

transMemTypes :: AbsKarel.MemTypes -> Result
transMemTypes x = case x of
  AbsKarel.MemTypeDMOS -> failure x
  AbsKarel.MemTypeDRAM -> failure x
  AbsKarel.MemTypeEmpty empty -> failure x

transReturnDataTypes :: AbsKarel.ReturnDataTypes -> Result
transReturnDataTypes x = case x of
  AbsKarel.RDTIdent ident -> failure x
  AbsKarel.RDTChar char -> failure x
  AbsKarel.RDTInt -> failure x
  AbsKarel.RDTReal -> failure x
  AbsKarel.RDTBool -> failure x
  AbsKarel.RDTVector -> failure x
  AbsKarel.RDTConfig -> failure x
  AbsKarel.RDTCommon -> failure x
  AbsKarel.RDTPos positiondatatypes integer -> failure x
  AbsKarel.RDTString -> failure x
  AbsKarel.RDTArray returnarrayindexs structuredarraytype -> failure x

transParameterDataTypes :: AbsKarel.ParameterDataTypes -> Result
transParameterDataTypes x = case x of
  AbsKarel.PDTIdent ident -> failure x
  AbsKarel.PDTChar char -> failure x
  AbsKarel.PDTInt -> failure x
  AbsKarel.PDTReal -> failure x
  AbsKarel.PDTBool -> failure x
  AbsKarel.PDTVector -> failure x
  AbsKarel.PDTVis -> failure x
  AbsKarel.PDTModel -> failure x
  AbsKarel.PDTCam -> failure x
  AbsKarel.PDTFile -> failure x
  AbsKarel.PDTConf -> failure x
  AbsKarel.PDTPath pathdatatype -> failure x
  AbsKarel.PDTCommon -> failure x
  AbsKarel.PDTPos positiondatatypes integer -> failure x
  AbsKarel.PDTString -> failure x
  AbsKarel.PDTArray datatypes structuredarraytype -> failure x

transDataTypes :: AbsKarel.DataTypes -> Result
transDataTypes x = case x of
  AbsKarel.DTString integer -> failure x
  AbsKarel.DTArray arrayindexings structuredarraytype -> failure x
  AbsKarel.DTStruct structuredarraytype -> failure x
  AbsKarel.DTParam parameterdatatypes -> failure x

transStructuredArrayType :: AbsKarel.StructuredArrayType -> Result
transStructuredArrayType x = case x of
  AbsKarel.SATShort -> failure x
  AbsKarel.SATByte -> failure x

transPathDataType :: AbsKarel.PathDataType -> Result
transPathDataType x = case x of
  AbsKarel.PathDTHeader ident -> failure x
  AbsKarel.PathDTNode ident -> failure x
  AbsKarel.PathDtEmpty empty -> failure x
  AbsKarel.PathDtHeaderExt ident1 ident2 -> failure x

transPositionDataTypes :: AbsKarel.PositionDataTypes -> Result
transPositionDataTypes x = case x of
  AbsKarel.PDTyPos -> failure x
  AbsKarel.PDTyXYZ -> failure x
  AbsKarel.PDTyJPos -> failure x
  AbsKarel.PDTyJPos1 -> failure x
  AbsKarel.PDTyJPos2 -> failure x
  AbsKarel.PDTyJPos3 -> failure x
  AbsKarel.PDTyJPos4 -> failure x
  AbsKarel.PDTyJPos5 -> failure x
  AbsKarel.PDTyJPos6 -> failure x
  AbsKarel.PDTyJPos7 -> failure x
  AbsKarel.PDTyJPos8 -> failure x
  AbsKarel.PDTyJPos9 -> failure x
  AbsKarel.PDTyXYZEXT -> failure x
  AbsKarel.PDTyGAssoc -> failure x

transBoolDataTypes :: AbsKarel.BoolDataTypes -> Result
transBoolDataTypes x = case x of
  AbsKarel.BDTTrue -> failure x
  AbsKarel.BDTFalse -> failure x

transArrayIndexing :: AbsKarel.ArrayIndexing -> Result
transArrayIndexing x = case x of
  AbsKarel.IntArrayIndex integer -> failure x

transReturnArrayIndex :: AbsKarel.ReturnArrayIndex -> Result
transReturnArrayIndex x = case x of
  AbsKarel.ReturnArrayInteger integer -> failure x
  AbsKarel.ReturnArrayAster -> failure x

transSign :: AbsKarel.Sign -> Result
transSign x = case x of
  AbsKarel.SignPlus -> failure x
  AbsKarel.SignMinus -> failure x
  AbsKarel.SignEmpty empty -> failure x

transLiteral :: AbsKarel.Literal -> Result
transLiteral x = case x of
  AbsKarel.LiteralInteger integer -> failure x
  AbsKarel.LiteralDouble double -> failure x
  AbsKarel.LiteralQuoted text -> failure x

transText :: AbsKarel.Text -> Result
transText x = case x of
  AbsKarel.TextString string -> failure x
  AbsKarel.TextQuotedString quotedstring -> failure x

transConstant :: AbsKarel.Constant -> Result
transConstant x = case x of
  AbsKarel.ConstLiteral literal -> failure x
  AbsKarel.ConstIdent ident -> failure x

transOptLineEnd :: AbsKarel.OptLineEnd -> Result
transOptLineEnd x = case x of
  AbsKarel.OptLineEndLineEnd lineend -> failure x
  AbsKarel.OptLineEndEmpty empty -> failure x
